# Generated by Django 6.0.7 on 2026-07-08 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=10, verbose_name='العام الدراسي')),
                ('semester_type', models.CharField(choices=[('first', 'الفصل الأول'), ('second', 'الفصل الثاني'), ('summer', 'الفصل الصيفي')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_semesters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
                'ordering': ['-created_at'],
                'unique_together': {('academic_year', 'semester_type')},
            },
        ),
    ]
