# Generated by Django 6.0.7 on 2026-07-08 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('semesters', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('student_description', models.TextField()),
                ('advisor_notes', models.TextField(blank=True)),
                ('resolution', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'معلقة'), ('in_progress', 'جاري العمل'), ('escalated', 'مُصعَّدة'), ('closed', 'مغلقة')], default='pending', max_length=20)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_complaints', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='semesters.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='students.student')),
            ],
            options={
                'verbose_name': 'شكوى',
                'verbose_name_plural': 'الشكاوى',
                'ordering': ['-created_at'],
            },
        ),
    ]
